new_repo_name: demo-repo-02
new_repo_description: for demo purpose 02
new_repo_tfvars_file: ["dev", "test"]
network_spoke_module: true
tfc_workspace_name: workspace-1
tfc_workspace_tags: ["tag1"]
tfc_workspace_var_set_name: Environment Variables 1
tfc_workspace_project_name: Project-1
tfc_new_projects: ["example1", "example2"]
tfc_new_var_sets: ["New Variable Set 1", "New Variable Set 2"]